<!-- The sensor graph popup -->
<div class="state_sensors" style="display:none;" >
<div class="state_close"><span>&#x2715;</span>Close</div>
<br class="clearboth" />
<div style="margin-left:25%;font-size:1.2em;font-weight:bold;color:#404040;">Describe Sensor States</div>
<div style="overflow: hidden;white-space: nowrap;"><span class="state_label">Open state:</span><span class="edible" style="width:15ex;" >Open</span></div>
<div style="overflow: hidden;white-space: nowrap;"><span class="state_label">Closed state:</span><span class="edible" style="width:15ex;">Closed</span></div>
<div class="state_graph_head"><span style="margin-left:10ex;"></span><div class="state_circle green" style="display:inline-block;"></div>&nbsp;&nbsp;<span style="vertical-align:super;">&rArr; Current State</span></div>
<div class="state_graph">
<div>Select graph</div>
<div class="state_circle green"  style="left: 240px; top:72px;"></div>
<div class="state_circle white"  style="left: 240px; top:170px;"></div>
</div></div>
<!-- end - The sensor graph popup -->
